import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
// import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { enUS, arSA } from '@clerk/localizations'

import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: Readonly<React.ReactNode>;
  params: Promise<{ lang: string }>;
}

export default async function RootLayout({ children, params }: Props) {
  const { lang } = await params;
  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }

  // TODO: Try to use this function to get static routes. ( not sure yet, do a search for that )
  // Enable static rendering
  /* setRequestLocale(lang) */

  return (
    <ClerkProvider
      localization={lang === "ar" ? arSA : enUS}
      appearance={{
        variables: {
          colorPrimary: "#C96342",
        },
      }}
    >
      <TRPCReactProvider>
        <html dir={lang === "ar" ? "rtl" : "ltr"} lang={lang} suppressHydrationWarning>
          {/* <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        > */}
          <body className={`antialiased`}>
            <NextIntlClientProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Toaster />
                {children}
              </ThemeProvider>
            </NextIntlClientProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
